---

settings:
  import/resolver: webpack

extends:
  - airbnb
  - "plugin:jest/recommended"
  - "plugin:react/recommended"

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

# rules:
#   react/prop-types: 0
rules:
  react/forbid-prop-types: 
    forbid: [any, array]